import { Link } from 'react-router-dom'
import type { ReactNode } from 'react'
import { projects } from '../data/projects'
import { ProjectCard } from '../components/projects/ProjectCard'
const CV_PATH = '/downloads/Alinaitwe_Kenneth_Bukenya_Updated_CV.pdf'
const credentials = [{ title: 'SQL Database', skill: 'SQL and database development', file: '/downloads/Kenneth_Bukenya_SQL_Database_Certificate.pdf' }, { title: 'Python Programming', skill: 'Python programming and automation', file: '/downloads/Kenneth_Bukenya_Python_Programming_Certificate.pdf' }, { title: 'Pandas', skill: 'Data manipulation and analysis', file: '/downloads/Kenneth_Bukenya_Pandas_Certificate.pdf' }, { title: 'NumPy', skill: 'Numerical computing', file: '/downloads/Kenneth_Bukenya_NumPy_Certificate.pdf' }, { title: 'Data Science', skill: 'Data science foundations', file: '/downloads/Kenneth_Bukenya_Data_Science_Certificate.pdf' }]
const capabilities = [['Full-Stack Development', 'React, TypeScript and Node.js applications shaped around real user and business workflows.'], ['Business Systems and ERP', 'Operational workflows connecting procurement, inventory, sales, finance, reporting and controls.'], ['Database Development and Management', 'PostgreSQL and SQL structures that keep business data traceable and useful.'], ['Data Analysis and Reporting', 'Decision-ready reporting, customer analysis, product analysis and forecasting foundations.'], ['Business Automation', 'Practical tools that reduce repetitive work and make routine decisions clearer.'], ['Machine Learning', 'An expanding capability developed through analysis and prototypes, without overstating production experience.'], ['APIs and Systems Integration', 'REST APIs and connected workflows across interfaces, services and data boundaries.'], ['Deployment and Content Management', 'Vite, Cloudflare Pages-compatible delivery and structured content systems where verified.']]
const Arrow = () => <span aria-hidden="true">→</span>
export function Page({ children }: { children: ReactNode }) { return <section className="section page"><div className="container narrow">{children}</div></section> }
export function AboutPage() { return <Page><div className="eyebrow">About Kenneth</div><h1>Business understanding is part of the build.</h1><p className="lead">I’m Kenneth Bukenya, a Full-Stack Developer and Business Systems Engineer focused on building secure, integrated digital solutions that improve business operations and decision-making.</p><div className="about-copy"><p>My work combines full-stack development, business systems and ERP workflows, database engineering, data analysis and reporting, and practical business automation. I build business applications, websites, APIs, reporting solutions and connected workflows using React, TypeScript, Node.js, Express, PostgreSQL, SQL and Python.</p><p>I am also developing my machine-learning capability through analysis and prototype work. It is an expanding area of practice, not a claim of broad production machine-learning experience.</p><p>I approach technology from a business-first perspective: understand the operational challenge, translate it into clear system rules and build a practical solution that improves accuracy, efficiency, accountability and access to reliable information.</p></div><div className="about-panels"><Link className="note cta-card" to="/contact"><div className="eyebrow">Availability</div><h2>Open to useful, well-scoped work.</h2><p>Employment and freelance projects across remote, hybrid, on-site, contract, full-time and part-time arrangements.</p><span className="text-link">Discuss an opportunity <Arrow /></span></Link><Link className="note cta-card" to="/skills"><div className="eyebrow">Hama Techservices</div><h2>A supporting service identity.</h2><p>Hama Techservices supports the presentation of practical systems, thoughtful engineering and business-aware delivery.</p><span className="text-link">Explore technology services <Arrow /></span></Link></div></Page> }
export function SkillsPage() { return <Page><div className="eyebrow">Skills and services</div><h1>Capabilities I bring to every project.</h1><p className="lead">I combine software development, business-process understanding, database engineering, analytics and automation to build solutions that work in real operating environments.</p><div className="services skill-grid">{capabilities.map(([title, description], index) => <article className="service" key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{description}</p></article>)}</div></Page> }
export function ProjectsPage() { return <section className="section page"><div className="container"><div className="eyebrow">Projects</div><h1>Systems built to solve real operational problems.</h1><p className="lead max">Explore how I’ve designed and developed business systems, websites, responsible AI workflows and data solutions—from understanding the problem to delivering a working solution.</p><div className="projects two">{projects.map(project => <ProjectCard key={project.slug} project={project} />)}</div></div></section> }
export function CredentialsPage() { return <Page><div className="eyebrow">Credentials</div><h1>Learning that supports the work.</h1><p className="lead">Selected certificates from the supplied portfolio materials, presented as evidence of focused study and applied capability.</p><p><a className="button primary" href={CV_PATH} download="Kenneth_Bukenya_CV.pdf">Download CV <Arrow /></a></p><div className="credentials">{credentials.map(item => <article className="credential" key={item.title}><div className="file-label">PDF certificate</div><h3>{item.title}</h3><p>{item.skill}</p><a className="text-link" href={item.file} download>View certificate <Arrow /></a></article>)}</div><div className="note"><div className="eyebrow">Participation certificate</div><p>The Frontier Engineering Challenge certificate is associated with the LeadBridgeAI materials and is presented as participation evidence, not as an award.</p></div></Page> }
export function ContactPage() { return <Page><div className="eyebrow">Contact</div><h1>Let’s talk about the work you need to make clearer.</h1><p className="lead">Choose the route that best matches what you need. Each action opens your email client or a verified professional profile; there is no hidden form submission.</p><div className="contact-options"><a className="contact-option" href="mailto:bukenny5@gmail.com?subject=Employment%20enquiry"><strong>Employment opportunities</strong><span>Discuss a full-time, part-time or contract role <Arrow /></span></a><a className="contact-option" href="mailto:bukenny5@gmail.com?subject=Freelance%20project%20enquiry"><strong>Freelance projects</strong><span>Share a practical project or workflow need <Arrow /></span></a><a className="contact-option" href="mailto:bukenny5@gmail.com?subject=Technical%20collaboration"><strong>Technical collaboration</strong><span>Talk through a systems, data or engineering idea <Arrow /></span></a><a className="contact-option" href="mailto:bukenny5@gmail.com?subject=General%20professional%20enquiry"><strong>General professional enquiry</strong><span>Send a direct email about another opportunity <Arrow /></span></a></div><div className="contact-card"><a href="mailto:bukenny5@gmail.com">Email: bukenny5@gmail.com</a><a href="https://www.linkedin.com/in/kenneth-bukenya-774502214" target="_blank" rel="noreferrer">LinkedIn</a><a href="https://github.com/bukenny5-lgtm" target="_blank" rel="noreferrer">GitHub</a></div></Page> }
export function NotFoundPage() { return <Page><div className="eyebrow">404</div><h1>That page isn’t part of this map.</h1><p className="lead">The address may be invalid, or the project identifier may not exist.</p><div className="actions"><Link className="button primary" to="/">Return home <Arrow /></Link><Link className="button secondary" to="/projects">View projects</Link></div></Page> }
