import { Link } from 'react-router-dom'
import { projects } from '../data/projects'
import { ProjectCard } from '../components/projects/ProjectCard'
const CV_PATH = '/downloads/Alinaitwe_Kenneth_Bukenya_Updated_CV.pdf'
const Arrow = () => <span aria-hidden="true">→</span>
const approach = [['01', 'Understand the operation', 'Start with the decisions, handoffs and rules that make the work move.'], ['02', 'Make the system dependable', 'Connect interfaces, data and controls so people can trust the result.'], ['03', 'Leave room to improve', 'Build a clear foundation that can grow without losing its shape.']]
const capabilities = [['Full-stack web applications', 'Interfaces, APIs and dependable application foundations built around real workflows.'], ['Business systems and ERP workflows', 'Connected operational processes covering inventory, sales, purchasing, reporting and controls.'], ['Database and reporting engineering', 'Structured data, reliable business rules and reporting that management can understand and trust.'], ['Automation, analytics and responsible AI', 'Practical automation and analysis that reduce repetitive work and support better decisions.']]

export function HomePage() {
  return <><section className="hero"><div className="container hero-grid"><div className="hero-copy-block"><div className="eyebrow">Full-Stack Developer &amp; Business Systems Engineer</div><h1>Building technology that understands the work behind the screen.</h1><p className="hero-copy">I turn real operational challenges into reliable software, connected workflows and decision-ready data. My work sits where business understanding, systems engineering and practical delivery meet.</p><div className="actions"><Link className="button primary" to="/projects">View My Work <Arrow /></Link><Link className="button secondary" to="/contact">Discuss a Project</Link><a className="button text-button" href={CV_PATH} download="Kenneth_Bukenya_CV.pdf">Download CV</a></div><p className="meta">● Based in Kampala, Uganda · Open to employment and freelance projects</p></div><div className="hero-portrait"><div className="portrait-frame"><img src="/assets/kenneth-bukenya-profile-2026.jpg" alt="Kenneth Bukenya, Full-Stack Developer and Business Systems Engineer" width="700" height="875" /></div><p className="portrait-caption">Practical systems, thoughtful engineering and business-aware delivery.</p></div></div></section><section className="section approach"><div className="container"><div className="section-head"><div><div className="eyebrow">How I work</div><h2>A clear path from context to confidence.</h2></div><p>Good software starts by understanding the work it needs to support.</p></div><div className="approach-grid">{approach.map(([number, title, description]) => <article className="approach-step" key={title}><span>{number}</span><div><h3>{title}</h3><p>{description}</p></div></article>)}</div></div></section><section className="section light"><div className="container"><div className="section-head"><div><div className="eyebrow">A connected skill set</div><h2>From business question to working system.</h2></div><p>Software development, business systems, data, automation and responsible experimentation.</p></div><div className="services">{capabilities.map(([title, description], index) => <div className="service" key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{description}</p></div>)}</div></div></section><section className="section"><div className="container"><div className="section-head"><div><div className="eyebrow">Selected work</div><h2>Systems built around real context.</h2></div><Link className="text-link" to="/projects">View all work <Arrow /></Link></div><div className="projects">{projects.map(project => <ProjectCard key={project.slug} project={project} />)}</div></div></section><section className="cta"><div className="container cta-inner"><h2>Let’s make the next version of the work easier to trust.</h2><Link className="button pale" to="/contact">Discuss a Project <Arrow /></Link></div></section></>
}
