import { BrowserRouter, Link, Route, Routes, useLocation, useParams } from 'react-router-dom'
import { Component, useEffect, useState, type ReactNode } from 'react'
import { createRoot } from 'react-dom/client'
import './styles.css'

type BoundaryState = { hasError: boolean; name: string; message: string }

class PortfolioErrorBoundary extends Component<{ children: ReactNode }, BoundaryState> {
  state: BoundaryState = { hasError: false, name: '', message: '' }
  static getDerivedStateFromError(error: unknown): BoundaryState { const value = error instanceof Error ? error : new Error(String(error)); return { hasError: true, name: value.name, message: value.message } }
  render() { if (this.state.hasError) return <div style={{ color: '#111', background: '#fff', minHeight: '100vh', padding: '2rem', fontFamily: 'Arial, sans-serif' }}><h1>The portfolio could not render.</h1><p><strong>{this.state.name}</strong>: {this.state.message}</p><p>Please report this diagnostic message to the developer.</p></div>; return this.props.children }
}

const CV_PATH = '/downloads/Alinaitwe_Kenneth_Bukenya_Updated_CV.pdf'
type Project = { slug: string; name: string; category: string; status: string; summary: string; cover: string; stack: string[]; highlights: string[]; live?: string }
const projects: Project[] = [
  { slug: 'kam-grains-erp', name: 'KAM GRAINS ERP', category: 'Integrated ERP and business management', status: 'Active development and operational implementation', summary: 'Integrated ERP for grain trading operations, connecting procurement, lot-based inventory, sales, payments, finance, reporting and audit controls.', cover: '/assets/kam-grains-erp-cover.png', stack: ['React', 'TypeScript', 'Node.js', 'PostgreSQL'], highlights: ['Delivery-based sales reporting', 'Lot-level stock traceability', 'Controlled journals and audit history'] },
  { slug: 'medlink-va', name: 'MedLink VA', category: 'Healthcare services platform', status: 'Implemented website foundation', summary: 'Responsive healthcare and training website with structured content, lead capture, certificate generation and public verification workflows.', cover: '/assets/medlink-va-cover.png', stack: ['React', 'TypeScript', 'Sanity', 'Cloudflare Pages'], highlights: ['CMS-backed content architecture', 'Server-side enquiry flows', 'Certificate issue-and-verify workflow'], live: 'https://medlinkva.com' },
  { slug: 'leadbridge-ai', name: 'LeadBridgeAI', category: 'Responsible AI prototype', status: 'Hackathon prototype and evaluation baseline', summary: 'Evaluation-first lead-engagement workflow that checks controlled evidence, applies policy boundaries and keeps every customer-facing response behind human approval.', cover: '/assets/leadbridge-ai-cover.png', stack: ['TypeScript', 'Node.js', 'JSON', 'Automated tests'], highlights: ['20-case synthetic evaluation', 'Verified read-only business context', 'Mandatory human approval'] },
  { slug: 'data-analytics-ml-automation', name: 'Data, Analytics, Machine Learning and Automation', category: 'Analysis and workflow automation', status: 'Selected work', summary: 'Practical analytics and automation spanning ERP reporting, customer segmentation, forecasting and small-business workflow tools.', cover: '/assets/erp-data-analytics-ml-cover.png', stack: ['Python', 'Pandas', 'NumPy', 'SQL'], highlights: ['Customer RFM segmentation', 'Sales and product analysis', 'Business workflow automation'] },
]

const capabilityGroups = [
  ['Full-Stack Development', 'React, TypeScript and Node.js applications shaped around real user and business workflows.'], ['Business Systems and ERP', 'Operational workflows connecting procurement, inventory, sales, finance, reporting and controls.'], ['Database Development and Management', 'PostgreSQL and SQL structures that keep business data traceable and useful.'], ['Data Analysis and Reporting', 'Decision-ready reporting, customer analysis, product analysis and forecasting foundations.'], ['Business Automation', 'Practical tools that reduce repetitive work and make routine decisions clearer.'], ['Machine Learning', 'Developing capability through analysis and prototypes, without overstating production ML experience.'], ['APIs and Systems Integration', 'REST APIs and connected workflows across interfaces, services and data boundaries.'], ['Deployment and Content Management', 'Vite, Cloudflare Pages-compatible delivery and structured content systems where verified.'],
]
const credentials = [
  { title: 'SQL Database', skill: 'SQL and database development', file: '/downloads/Kenneth_Bukenya_SQL_Database_Certificate.pdf' }, { title: 'Python Programming', skill: 'Python programming and automation', file: '/downloads/Kenneth_Bukenya_Python_Programming_Certificate.pdf' }, { title: 'Pandas', skill: 'Data manipulation and analysis', file: '/downloads/Kenneth_Bukenya_Pandas_Certificate.pdf' }, { title: 'NumPy', skill: 'Numerical computing', file: '/downloads/Kenneth_Bukenya_NumPy_Certificate.pdf' }, { title: 'Data Science', skill: 'Data science foundations', file: '/downloads/Kenneth_Bukenya_Data_Science_Certificate.pdf' },
]
const ArrowRight = () => <span aria-hidden="true">→</span>
const Check = () => <span aria-hidden="true">✓</span>

function Layout({ children }: { children: ReactNode }) {
  const [open, setOpen] = useState(false); const location = useLocation()
  useEffect(() => setOpen(false), [location.pathname])
  useEffect(() => { const closeOnEscape = (event: KeyboardEvent) => { if (event.key === 'Escape') setOpen(false) }; window.addEventListener('keydown', closeOnEscape); return () => window.removeEventListener('keydown', closeOnEscape) }, [])
  return <><header><div className="container nav"><Link className="brand" to="/"><b>KB</b>Kenneth Bukenya</Link><button className="menu" onClick={() => setOpen(value => !value)} aria-label={open ? 'Close navigation' : 'Open navigation'} aria-expanded={open} aria-controls="primary-navigation">{open ? '×' : '☰'}</button><nav id="primary-navigation" className={open ? 'open' : ''}>{[['/', 'Home'], ['/about', 'About'], ['/projects', 'Projects'], ['/skills', 'Skills'], ['/credentials', 'Credentials'], ['/contact', 'Contact']].map(([href, label]) => <Link key={href} to={href}>{label}</Link>)}<a className="nav-cta" href={CV_PATH} download="Kenneth_Bukenya_CV.pdf">Download CV <ArrowRight /></a><Link className="nav-cta" to="/contact">Discuss a project <ArrowRight /></Link></nav></div></header><main>{children}</main><Footer /></>
}

function Card({ project }: { project: Project }) { return <article className="card"><Link to={`/work/${project.slug}`}><div className="cover" style={{ backgroundImage: `url(${project.cover})` }}><span>{project.status}</span></div><div className="card-body"><div className="eyebrow">{project.category}</div><h3>{project.name}</h3><p>{project.summary}</p><div className="tags">{project.stack.map(item => <small key={item}>{item}</small>)}</div><span className="text-link">Read case study <ArrowRight /></span></div></Link>{project.live && <a className="live-link" href={project.live} target="_blank" rel="noreferrer">Visit verified live site <ArrowRight /></a>}</article> }

function Home() { return <><section className="hero"><div className="container hero-grid"><div><div className="eyebrow">Full-Stack Developer &amp; Business Systems Engineer</div><h1>Building technology that understands the work behind the screen.</h1><p className="hero-copy">I turn real operational challenges into reliable software, connected workflows and decision-ready data. My work sits where business understanding, systems engineering and practical delivery meet.</p><div className="actions"><Link className="button primary" to="/projects">View my work <ArrowRight /></Link><Link className="button secondary" to="/contact">Discuss a project</Link><a className="button secondary" href={CV_PATH} download="Kenneth_Bukenya_CV.pdf">Download CV</a></div><p className="meta">● Based in Kampala, Uganda · Open to employment and freelance projects</p></div><div className="panel"><div className="eyebrow light">How I work</div>{['Understand the operation', 'Make the system dependable', 'Leave room to improve'].map((item, index) => <div className="principle" key={item}><span>0{index + 1}</span><div><strong>{item}</strong><p>{['Start with the decisions, handoffs and rules that make the work move.', 'Connect interfaces, data and controls so people can trust the result.', 'Build a clear foundation that can grow without losing its shape.'][index]}</p></div></div>)}</div></div></section><section className="section light"><div className="container"><div className="section-head"><div><div className="eyebrow">A connected skill set</div><h2>From business question to working system.</h2></div><p>Software development, databases, process analysis, automation, reporting and developing machine-learning capability.</p></div><div className="services">{capabilityGroups.slice(0, 4).map(([title, description], index) => <div className="service" key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{description}</p></div>)}</div></div></section><section className="section"><div className="container"><div className="section-head"><div><div className="eyebrow">Selected work</div><h2>Systems built around real context.</h2></div><Link className="text-link" to="/projects">View all work <ArrowRight /></Link></div><div className="projects">{projects.map(project => <Card key={project.slug} project={project} />)}</div></div></section><section className="section light"><div className="container"><div className="section-head"><div><div className="eyebrow">Credentials</div><h2>Learning that supports the work.</h2></div><Link className="text-link" to="/credentials">View credentials <ArrowRight /></Link></div><div className="tags">{credentials.slice(0, 3).map(item => <small key={item.title}>{item.title}</small>)}</div></div></section><section className="cta"><div className="container cta-inner"><h2>Let’s make the next version of the work easier to trust.</h2><Link className="button pale" to="/contact">Discuss a project <ArrowRight /></Link></div></section></> }
function Page({ children }: { children: ReactNode }) { return <section className="section page"><div className="container narrow">{children}</div></section> }
function About() { return <Page><div className="eyebrow">About Kenneth</div><h1>Business understanding is part of the build.</h1><p className="lead">I’m Kenneth Bukenya, a Full-Stack Developer and Business Systems Engineer focused on building secure, integrated digital solutions that improve business operations and decision-making.</p><p>My work combines full-stack development, business systems and ERP workflows, database engineering, data analysis and reporting, and practical business automation. I build business applications, websites, APIs, reporting solutions and connected workflows using React, TypeScript, Node.js, Express, PostgreSQL, SQL and Python.</p><p>I am also developing my machine-learning capability through analysis and prototype work. I describe that work carefully: it supports my growth and problem-solving practice, without claiming broad production machine-learning experience.</p><p>I approach technology from a business-first perspective: understand the operational challenge, translate it into clear system rules and build a practical solution that improves accuracy, efficiency, accountability and access to reliable information.</p><p>I’m open to employment and freelance projects across remote, hybrid, on-site, contract, full-time and part-time arrangements. Hama Techservices is the supporting service identity for this work.</p></Page> }
function Skills() { return <Page><div className="eyebrow">Skills and services</div><h1>Tools and thinking that work together.</h1><p className="lead">A practical capability set spanning software, business systems, data, automation and responsible experimentation.</p><div className="services skill-grid">{capabilityGroups.map(([title, description], index) => <div className="service" key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{description}</p></div>)}</div></Page> }
function Work() { return <section className="section page"><div className="container"><div className="eyebrow">Selected work</div><h1>Practical systems, carefully described.</h1><p className="lead max">These case studies use verified project evidence. Private repositories, synthetic prototypes and planned capabilities are labelled clearly.</p><div className="projects two">{projects.map(project => <Card key={project.slug} project={project} />)}</div></div></section> }
function Detail() { const { slug } = useParams(); const project = projects.find(item => item.slug === slug); if (!project) return <NotFound />; return <section className="section page"><div className="container"><Link className="back" to="/projects">← Back to projects</Link><div className="case"><div><div className="eyebrow">{project.category}</div><h1>{project.name}</h1><p className="lead">{project.summary}</p><span className="status">{project.status}</span>{project.live && <p><a className="text-link" href={project.live} target="_blank" rel="noreferrer">Verified live site <ArrowRight /></a></p>}</div><img src={project.cover} alt={`${project.name} project cover`} /></div><div className="case-grid"><article><h2>What this demonstrates</h2><p>This case study is presented from verified project documentation and approved portfolio assets. It focuses on engineering choices and business context rather than unverified outcomes.</p><div className="highlights">{project.highlights.map(item => <div key={item}><Check />{item}</div>)}</div><h2>Technology</h2><div className="tags">{project.stack.map(item => <small key={item}>{item}</small>)}</div></article><aside className="note"><div className="eyebrow">Evidence boundary</div><p>Private repositories, synthetic evaluations and operational systems are described conservatively. No private credentials, source paths or customer identities are exposed.</p></aside></div></div></section> }
function Credentials() { return <Page><div className="eyebrow">Credentials</div><h1>Learning that supports the work.</h1><p className="lead">Selected certificates from the supplied portfolio materials, presented as evidence of focused study and applied capability.</p><p><a className="button primary" href={CV_PATH} download="Kenneth_Bukenya_CV.pdf">Download CV <ArrowRight /></a></p><div className="credentials">{credentials.map(item => <article className="credential" key={item.title}><h3>{item.title}</h3><p>{item.skill}</p><a className="text-link" href={item.file} download>View or download certificate <ArrowRight /></a></article>)}</div><div className="note"><div className="eyebrow">Participation evidence</div><p>The Frontier Engineering Challenge certificate is associated with the LeadBridgeAI materials and is presented as participation evidence, not as an award. It is not presented as a general professional credential here.</p></div></Page> }
function Contact() { return <Page><div className="eyebrow">Contact</div><h1>Let’s talk about the work you need to make clearer.</h1><p className="lead">I’m open to employment and freelance projects across remote, hybrid, on-site, contract, full-time and part-time arrangements.</p><div className="actions"><a className="button primary" href="mailto:bukenny5@gmail.com?subject=Employment%20enquiry">Employment enquiry</a><a className="button secondary" href="mailto:bukenny5@gmail.com?subject=Freelance%20project%20enquiry">Freelance enquiry</a></div><div className="contact-card"><a href="mailto:bukenny5@gmail.com">Email: bukenny5@gmail.com</a><a href="https://www.linkedin.com/in/kenneth-bukenya-774502214" target="_blank" rel="noreferrer">LinkedIn</a><a href="https://github.com/bukenny5-lgtm" target="_blank" rel="noreferrer">GitHub</a></div><p className="note">Direct contact actions open your email client. No form submission or artificial success state is claimed.</p></Page> }
function NotFound() { return <Page><div className="eyebrow">404</div><h1>That page isn’t part of this map.</h1><p className="lead">The address may be invalid, or the project identifier may not exist.</p><div className="actions"><Link className="button primary" to="/">Return home <ArrowRight /></Link><Link className="button secondary" to="/projects">View projects</Link></div></Page> }
function Footer() { return <footer><div className="container foot"><div><div className="eyebrow light">Hama Techservices</div><h2>Technology that makes the work clearer.</h2><p>Practical systems, thoughtful engineering and business-aware delivery from Kampala, Uganda.</p></div><div className="foot-links"><Link to="/about">About Kenneth</Link><Link to="/projects">Selected work</Link><Link to="/credentials">Credentials</Link><Link to="/contact">Contact Kenneth</Link><a href="mailto:bukenny5@gmail.com">Email Kenneth</a><a href="https://www.linkedin.com/in/kenneth-bukenya-774502214" target="_blank" rel="noreferrer">LinkedIn</a><a href="https://github.com/bukenny5-lgtm" target="_blank" rel="noreferrer">GitHub</a></div></div><div className="container fine">© {new Date().getFullYear()} Kenneth Bukenya · Full-Stack Developer &amp; Business Systems Engineer</div></footer> }
function App() { return <Layout><Routes><Route path="/" element={<Home />} /><Route path="/about" element={<About />} /><Route path="/work" element={<Work />} /><Route path="/projects" element={<Work />} /><Route path="/skills" element={<Skills />} /><Route path="/work/:slug" element={<Detail />} /><Route path="/credentials" element={<Credentials />} /><Route path="/contact" element={<Contact />} /><Route path="*" element={<NotFound />} /></Routes></Layout> }
export default function Root() { return <BrowserRouter><App /></BrowserRouter> }
const rootElement = document.getElementById('root')
if (!rootElement) throw new Error('Portfolio root element #root was not found.')
createRoot(rootElement).render(<PortfolioErrorBoundary><Root /></PortfolioErrorBoundary>)
